trigger:
  branches:
    include: [main]


variables:
- group: kv-dockerhub
- name: imageRepo
  value: $(DOCKERHUB_REPO)
- name: tag
  value: $(Build.BuildId) 


stages:
  - stage: CI
    displayName: PIPO- Build, Test, Scan and Push 
    jobs:
      - job: build_test_push 
        pool:
          name: Default
          demands:
            - docker
        steps:
        - checkout: self 
          clean: true 
        - script: |
            set -e 
            python3 -m venv .venv
            .venv/bin/python -m pip install --upgrade pip
            .venv/bin/pip install -r requirements.txt
          
          displayName: Install deps in venv & run tests 
        
        - task: Docker@2
          displayName: Build & Push to Docker Hub
          inputs:
            command: buildAndPush
            containerRegistry: 'dockerhubconnection'           
            repository: '$(imageRepo)'                   
            Dockerfile: '**/Dockerfile'
            tags: |
              $(tag)
              latest