trigger:
  branches:
    include: [ main ]

pool:
  name: Default          # ou le nom de ton pool
  demands:               # s'assure que docker est présent
    - docker

variables:
  imageName: 'fastapi-app'
  tag: '$(Build.BuildId)'

stages:
- stage: CI
  displayName: Build & Test
  jobs:
  - job: build_test
    displayName: Run unit tests and build image
    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest -q
      displayName: Install & Test

    # (Optionnel) Lint & sécurité
    - script: |
        pip install flake8 bandit
        flake8 app --max-line-length=100
        bandit -r app -q
      displayName: Lint & Security Scan

    - script: |
        docker build -t $(imageName):$(tag) .
      displayName: Docker build

    # (Optionnel) tag "latest" local
    - script: |
        docker tag $(imageName):$(tag) $(imageName):latest
      displayName: Tag latest

- stage: CD
  displayName: Deploy to Local Linux
  dependsOn: CI
  jobs:
  - job: deploy
    displayName: Compose Up
    steps:
    - checkout: self
      clean: true

    # Mettre à jour le TAG et redémarrer le service avec docker compose
    - script: |
        export TAG=$(tag)
        echo "Using tag: $TAG"
        docker compose pull || true    # si tu utilisais un registry
        docker compose down || true
        TAG=$TAG docker compose up -d --remove-orphans
        docker image prune -f
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: Docker Compose Up