resources:
  pipelines:
  - pipeline: ci_run
    source: 'pipo-ci'        
    trigger: true               

variables:
- group: kv-dockerhub

stages:
- stage: CD_Canary
  displayName: Canary then Full rollout
  dependsOn: CI
  jobs:
  - deployment: Deploy_Canary
    displayName: Canary deploy (tag=canary)
    environment:
      name: prod
      resourceType: VirtualMachine
      tags: ['canary']          
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Docker@2
            displayName: Docker Hub login
            inputs:
              command: login
              containerRegistry: 'servicedockerhubconnection'

          - script: |
              set -e
              export DOCKERHUB_REPO="$(DOCKERHUB_REPO)"
              export TAG="$(Build.BuildId)"
              echo "CANARY → docker.io/${DOCKERHUB_REPO}:${TAG}"
              DOCKERHUB_REPO="$DOCKERHUB_REPO" TAG="$TAG" \
                docker compose -f /opt/fastapi/docker-compose.yml pull
              DOCKERHUB_REPO="$DOCKERHUB_REPO" TAG="$TAG" \
                docker compose -f /opt/fastapi/docker-compose.yml up -d --remove-orphans
            displayName: Pull & Up (canary)

          - script: |
              set -e
              echo "Smoke test on canary node"
              curl -fsS http://localhost:8000/health | grep -q '"status":"ok"'
            displayName: Smoke test (canary)
      
  - deployment: Deploy_Stable
    displayName: Rollout to stable (tags=stable)
    dependsOn: Deploy_Canary
    condition: succeeded()             # ne déploie sur stable que si canary est OK
    environment:
      name: prod
      resourceType: VirtualMachine
      tags: ['stable']
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Docker@2
            displayName: Docker Hub login
            inputs:
              command: login
              containerRegistry: 'servicedockerhubconnection'

          - script: |
              set -e
              export DOCKERHUB_REPO="$(DOCKERHUB_REPO)"
              export TAG="$(Build.BuildId)"
              echo "STABLE → docker.io/${DOCKERHUB_REPO}:${TAG}"
              DOCKERHUB_REPO="$DOCKERHUB_REPO" TAG="$TAG" \
                docker compose -f /opt/fastapi/docker-compose.yml pull
              DOCKERHUB_REPO="$DOCKERHUB_REPO" TAG="$TAG" \
                docker compose -f /opt/fastapi/docker-compose.yml up -d --remove-orphans
              docker image prune -f
            displayName: Pull & Up (stable)