trigger:
  branches:
    include: [main]

pool:
  name: Default          # ou le nom de ton pool
  demands:               # s'assure que docker est présent
    - docker

variables:
- group: kv-kv-dockerhub
- name: imageRepo
  value: $(DOCKERHUB_REPO)
- name: tag
  value: $(Build.BuildId) 


stages:
  - stage: CI
    displayName: PIPO- Build, Test, Scan and Push 
    jobs:
      - job: build_test_push 

        steps:
        - checkout: self 
          clean: true 
        - script: |
            set -e 
            python3 -m venv .venv
            .venv/bin/python -m pip install --upgrade pip
            .venv/bin/pip install -r requirements.txt
          
          displayName: Install deps in venv & run tests 
        
        - task: Docker@2 
          displayName: Build Image 
          inputs:
            command: build 
            repository: $(imageRepo)
            containerRegistry: sc-dockerhub 
            Dockerfile: '**/Dockerfile'
            tags: |
              $(tag)
              latest
      
        - script: |
            set -e
            curl -L https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz \
            | tar zx -C /usr/local/bin trivy
            /usr/local/bin/trivy image --severity HIGH,CRITICAL --no-progress --exit-code 0 docker.io/$(imageRepo):$(tag)
            displayName: Trivy scan (warn only)
        
        