trigger:
  branches:
    include: [main]


variables:
- group: kv-dockerhub
- name: imageRepo
  value: $(DOCKERHUB_REPO)
- name: tag
  value: $(Build.BuildId) 


stages:
  - stage: CI
    displayName: PIPO- Build, Test, Scan and Push 
    jobs:
      - job: build_test_push 
        pool:
          name: pipo-pool
          demands:
            - docker
        steps:
        - checkout: self 
          clean: true 
        - script: |
            set -e 
            python3 -m venv .venv
            .venv/bin/python -m pip install --upgrade pip
            .venv/bin/pip install -r requirements.txt
          
          displayName: Install deps in venv & run tests 

        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            command: build
            repository: $(imageRepo)
            Dockerfile: '**/Dockerfile'
            tags: |
              $(tag)
              latest

        - script: |
            set -e
            trivy image --severity HIGH,CRITICAL --no-progress --exit-code 0 princemitnick/fast-azure-pipeline:1
          
          displayName: Scan Image with Trivy
        
        - task: Docker@2
          displayName: Push Image to Docker Hub
          inputs:
            command: push
            containerRegistry: 'servicedockerhubconnection'           
            repository: '$(imageRepo)'                   
            tags: |
              $(tag)
              latest

  - stage: CD
    displayName: Deploy to prod-linux
    dependsOn: CI
    jobs:
    - deployment: DeployFastAPI
      displayName: Pull & Compose Up on Environment VM
      environment:
        name: prod                
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Docker@2
              displayName: Docker Hub login
              inputs:
                command: login
                containerRegistry: 'servicedockerhubconnection'   

            - script: |
                set -e
                export DOCKERHUB_REPO="$(DOCKERHUB_REPO)"  
                export TAG="$(Build.BuildId)"
                echo "Deploying image: docker.io/${DOCKERHUB_REPO}:${TAG}"

                # Pull latest image for this build
                TAG="$TAG" DOCKERHUB_REPO="$DOCKERHUB_REPO" \
                  docker compose -f /opt/fastapi/docker-compose.yml pull

                TAG="$TAG" DOCKERHUB_REPO="$DOCKERHUB_REPO" \
                  docker compose -f /opt/fastapi/docker-compose.yml up -d --remove-orphans

                docker image prune -f
              displayName: Pull & Compose Up
